// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// someCPPcode
SEXP someCPPcode(SEXP r, SEXP device);
RcppExport SEXP rcppcuda_someCPPcode(SEXP rSEXP, SEXP device) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type r(rSEXP);
    __result = Rcpp::wrap(someCPPcode(r, device));
    return __result;
END_RCPP
}
