# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Function \code{someCPPcode}
#' @description Run some C++ code to change 
#' the slots in argument object \code{r}.
#' 
#' @export
#' @rdname someCPPcode
#' @aliases someCPPcode
#'
#' @param r a \code{MyClass} object.
someCPPcode <- function(r) {
    .Call('rcppcuda_someCPPcode', PACKAGE = 'rcppcuda', r)
}

